[package]
name = "executor-lib"
version = "0.1.0"
build = "build.rs"
edition = "2021"

[dependencies]
anyhow = "1.0.98"

[build-dependencies]
vergen = { version = "9.0.6", features = ["build", "cargo", "rustc", "si"] }
anyhow = "1.0.98"
tonic-prost-build = "0.14.0"

