//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::{
    attributes_index::Entity as AttributesIndex,
    chunked_content::Entity as ChunkedContent,
    content::Entity as Content,
    data_repository::Entity as DataRepository,
    events::Entity as Events,
    extraction_event::Entity as ExtractionEvent,
    extractors::Entity as Extractors,
    index::Entity as Index,
    work::Entity as Work,
};
