[package]
name = "executor_api"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = {workspace = true}
prost = {workspace = true}
tokio = {workspace = true}
tokio-stream = {workspace = true}
futures = {workspace = true}
clap = {workspace = true}
tonic-reflection = {workspace = true}
tracing = { workspace = true }

[build-dependencies]
tonic-build = {workspace = true}