---
apiVersion: v1
kind: Service
metadata:
  name: extractor
  labels:
    app.kubernetes.io/component: extractor
spec:
  ports:
    - port: 9501
  selector:
    app.kubernetes.io/component: extractor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor
  labels:
    app.kubernetes.io/component: extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: extractor
  template:
    metadata:
      labels:
        app.kubernetes.io/component: extractor
    spec:
      containers:
        - name: extractor
          image: tensorlake/extractor:latest

          command: ['/bin/bash', '-c']
          args:
            - |-
              indexify-extractor join-server \
              --coordinator-addr coordinator:8950 \
              --ingestion-addr api:8900 \
              --advertise-addr $(hostname | cut -d"-" -f1):9501 \
              --listen-port 9501
