[package]
name = "task_scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
serde.workspace = true
rand.workspace = true
serde_json.workspace = true
data_model.workspace = true
state_store.workspace = true
tracing.workspace = true
im.workspace = true

