{{- if .Values.server.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  {{- if .Values.server.ingress.annotations}}
  annotations:
    {{- toYaml .Values.server.ingress.annotations | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: api
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: indexify-server
                port:
                  number: 8900
{{- end }}
