{{- if .Values.minio.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: blob-creds
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
{{- else }}
{{- if and .Values.blobStore.config.s3.accessKey .Values.blobStore.config.s3.secretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: blob-creds
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.blobStore.config.s3.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.blobStore.config.s3.secretKey }}
{{- else}}
  {{- fail "blob store credentials are not set" }}
{{- end }}
{{- end }}
