FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    update-ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /indexify

# The binary will be copied in during the Docker build via buildx
# The TARGETARCH build arg is automatically set by Docker buildx
ARG TARGETARCH
COPY indexify-server-${TARGETARCH} /indexify/indexify-server
RUN chmod +x /indexify/indexify-server

ENTRYPOINT [ "/indexify/indexify-server" ]
