FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends \
    ca-certificates \
    build-essential pkg-config clang \
    g++ \
    git curl

RUN curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh && \
    bash -E nodesource_setup.sh && \
    apt-get install --assume-yes --no-install-recommends nodejs