{
 "title": "ind",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "bytes uploaded",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(content_bytes_uploaded[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bytes extracted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "rate(content_bytes_extracted[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "conent uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(content_uploads[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tasks in progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "targets": [
    { "expr": "tasks_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "bytes extracted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(content_bytes_extracted[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}