state_store_path = "indexify_server_state"
listen_addr = "0.0.0.0:8900"

[telemetry]
enable_tracing = false
enable_metrics = false
# Shared OTLP endpoint for both traces and metrics
# If specified, both traces and metrics will be sent to this endpoint
endpoint = "http://localhost:4317"
# Metrics export interval in seconds (defaults to 10 if not specified)
metrics_interval = 5
# Optional path to write local logs to a rotating file
local_log_file = "/tmp/indexify/local.log"
# Instance ID for this Indexify server instance
# Used as a metric attribute "indexify.instance.id"
instance_id = "indexify-server-1"

# List of targets and their log levels for local logging
[telemetry.local_log_targets]
scheduler = "debug"

# Executor label sets configuration.
#
# Each label set defines a collection of key-value pairs that can be
# used to categorize and filter executors.
#
# If no executor label sets are configured below, any executor labels
# are allowed.
[[labels]]
region = "us-west-2"
instance_type = "gpu"
gpu_model = "nvidia-a100"

[[labels]]
region = "us-east-1"
instance_type = "cpu"

[[labels]]
region = "eu-west-1"
instance_type = "gpu"
gpu_model = "nvidia-h100"
