state_store_path = "indexify_server_state"
listen_addr = "0.0.0.0:8900"

[telemetry]
enable_tracing = false
enable_metrics = false
# Shared OTLP endpoint for both traces and metrics
# If specified, both traces and metrics will be sent to this endpoint
endpoint = "http://localhost:4317"
# Metrics export interval in seconds (defaults to 10 if not specified)
metrics_interval = 5
# Optional path to write local logs to a rotating file
local_log_file = "/tmp/indexify/local.log"

# List of targets and their log levels for local logging
[telemetry.local_log_targets]
scheduler = "debug"
