apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: quay.io/minio/minio
    newTag: latest

resources:
  - blob-store.yaml

patches:
  - path: config.yaml
  - path: api.yaml
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=extractor
    path: extractor.yaml
