---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexify-server
  labels:
    app.kubernetes.io/component: indexify-server
spec:
  template:
    spec:
      containers:
        - name: indexify-server
          env:
            - name: AWS_ENDPOINT
              value: http://blob-store:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: blob-store
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: blob-store
                  key: AWS_SECRET_ACCESS_KEY
