export { default as NamespacesPage } from './NamespacesPage'
export { default as ApplicationsListPage } from './ComputeGraphsPage'
// export { default as IndividualComputeGraphPage } from './IndividualComputeGraphPage'
export { default as IndividualInvocationPage } from './IndividualInvocationPage'
export { default as ExecutorsPage } from './ExecutorsPage'
