FROM --platform=linux/arm64/v8 python:3.8.16 AS python

FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

RUN apt-get update && apt-get -y install python3.8 protobuf-compiler

COPY --from=python /usr/local/lib/ /opt/sysroot/usr/lib/

ENV RUSTFLAGS="-L /opt/sysroot/usr/lib"
