FROM tensorlake/builder as builder
FROM ubuntu:22.04

RUN apt-get update

RUN apt install -y libssl-dev python3-dev python3-pip

WORKDIR /indexify

COPY --from=builder /indexify-build/target/release/indexify ./
