FROM tensorlake/builder AS builder
FROM ubuntu:22.04

RUN apt update

RUN apt install -y libssl-dev python3-dev ca-certificates

RUN update-ca-certificates

WORKDIR /indexify

COPY --from=builder /indexify-build/target/release/indexify ./

COPY sample_config.yaml ./config/indexify.yaml

ENV PATH="/indexify:${PATH}"

COPY ./scripts/docker_compose_start.sh .

ENTRYPOINT [ "/indexify/indexify" ]