FROM {{ image_name }}

RUN apt-get update

RUN apt-get install -y  {{ system_dependencies }}

RUN pip3 install --no-input {{ additional_pip_flags }} {{ python_dependencies }}

COPY . /indexify/

COPY indexify.yaml indexify.yaml

{{ additional_dev_setup }}

ENTRYPOINT [ "/indexify/indexify" ]