apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: indexify-secrets
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexify-secrets
                  key: postgres_password
            - name: POSTGRES_DB
              value: indexify
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume
              subPath: pgdata
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
