# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from indexify.proto import executor_api_pb2 as indexify_dot_proto_dot_executor__api__pb2

GRPC_GENERATED_VERSION = "1.78.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in indexify/proto/executor_api_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ExecutorAPIStub(object):
    """════════════════════════════════════════════
    REMOVED MESSAGES (kept as reserved comments)
    ════════════════════════════════════════════

    GetCommandStreamRequest removed — replaced by PollCommandsRequest.
    ReportCommandResponsesRequest/Response removed — folded into HeartbeatRequest.
    ReportAllocationActivitiesRequest/Response removed — folded into HeartbeatRequest.
    AllocationStreamRequest removed — log entries folded into HeartbeatRequest,
    results delivered via PollAllocationResultsResponse.
    AllocationStreamResponse removed — replaced by PollAllocationResultsResponse.

    Internal API for scheduling and running allocations on Executors. Executors are acting as clients of this API.
    Server is responsible for scheduling allocations on Executors and Executors are responsible for running the allocations.

    Rename with caution. Existing clients won't find the service if the service name changes. A HTTP2 ingress proxy
    might use the service name in it HTTP2 path based routing rules. See how gRPC uses service names in its HTTP2 paths
    at https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.heartbeat = channel.unary_unary(
            "/executor_api_pb.ExecutorAPI/heartbeat",
            request_serializer=indexify_dot_proto_dot_executor__api__pb2.HeartbeatRequest.SerializeToString,
            response_deserializer=indexify_dot_proto_dot_executor__api__pb2.HeartbeatResponse.FromString,
            _registered_method=True,
        )
        self.poll_commands = channel.unary_unary(
            "/executor_api_pb.ExecutorAPI/poll_commands",
            request_serializer=indexify_dot_proto_dot_executor__api__pb2.PollCommandsRequest.SerializeToString,
            response_deserializer=indexify_dot_proto_dot_executor__api__pb2.PollCommandsResponse.FromString,
            _registered_method=True,
        )
        self.poll_allocation_results = channel.unary_unary(
            "/executor_api_pb.ExecutorAPI/poll_allocation_results",
            request_serializer=indexify_dot_proto_dot_executor__api__pb2.PollAllocationResultsRequest.SerializeToString,
            response_deserializer=indexify_dot_proto_dot_executor__api__pb2.PollAllocationResultsResponse.FromString,
            _registered_method=True,
        )


class ExecutorAPIServicer(object):
    """════════════════════════════════════════════
    REMOVED MESSAGES (kept as reserved comments)
    ════════════════════════════════════════════

    GetCommandStreamRequest removed — replaced by PollCommandsRequest.
    ReportCommandResponsesRequest/Response removed — folded into HeartbeatRequest.
    ReportAllocationActivitiesRequest/Response removed — folded into HeartbeatRequest.
    AllocationStreamRequest removed — log entries folded into HeartbeatRequest,
    results delivered via PollAllocationResultsResponse.
    AllocationStreamResponse removed — replaced by PollAllocationResultsResponse.

    Internal API for scheduling and running allocations on Executors. Executors are acting as clients of this API.
    Server is responsible for scheduling allocations on Executors and Executors are responsible for running the allocations.

    Rename with caution. Existing clients won't find the service if the service name changes. A HTTP2 ingress proxy
    might use the service name in it HTTP2 path based routing rules. See how gRPC uses service names in its HTTP2 paths
    at https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md.
    """

    def heartbeat(self, request, context):
        """Heartbeat: liveness + optional state sync + batched reports
        (command responses, allocation outcomes, log entries).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def poll_commands(self, request, context):
        """Long-poll for pending commands. Server holds request open until
        commands are available or ~5 min timeout.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def poll_allocation_results(self, request, context):
        """Long-poll for pending function call results. Server holds request
        open until results are available or ~5 min timeout.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExecutorAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "heartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.heartbeat,
            request_deserializer=indexify_dot_proto_dot_executor__api__pb2.HeartbeatRequest.FromString,
            response_serializer=indexify_dot_proto_dot_executor__api__pb2.HeartbeatResponse.SerializeToString,
        ),
        "poll_commands": grpc.unary_unary_rpc_method_handler(
            servicer.poll_commands,
            request_deserializer=indexify_dot_proto_dot_executor__api__pb2.PollCommandsRequest.FromString,
            response_serializer=indexify_dot_proto_dot_executor__api__pb2.PollCommandsResponse.SerializeToString,
        ),
        "poll_allocation_results": grpc.unary_unary_rpc_method_handler(
            servicer.poll_allocation_results,
            request_deserializer=indexify_dot_proto_dot_executor__api__pb2.PollAllocationResultsRequest.FromString,
            response_serializer=indexify_dot_proto_dot_executor__api__pb2.PollAllocationResultsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "executor_api_pb.ExecutorAPI", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "executor_api_pb.ExecutorAPI", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ExecutorAPI(object):
    """════════════════════════════════════════════
    REMOVED MESSAGES (kept as reserved comments)
    ════════════════════════════════════════════

    GetCommandStreamRequest removed — replaced by PollCommandsRequest.
    ReportCommandResponsesRequest/Response removed — folded into HeartbeatRequest.
    ReportAllocationActivitiesRequest/Response removed — folded into HeartbeatRequest.
    AllocationStreamRequest removed — log entries folded into HeartbeatRequest,
    results delivered via PollAllocationResultsResponse.
    AllocationStreamResponse removed — replaced by PollAllocationResultsResponse.

    Internal API for scheduling and running allocations on Executors. Executors are acting as clients of this API.
    Server is responsible for scheduling allocations on Executors and Executors are responsible for running the allocations.

    Rename with caution. Existing clients won't find the service if the service name changes. A HTTP2 ingress proxy
    might use the service name in it HTTP2 path based routing rules. See how gRPC uses service names in its HTTP2 paths
    at https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md.
    """

    @staticmethod
    def heartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/executor_api_pb.ExecutorAPI/heartbeat",
            indexify_dot_proto_dot_executor__api__pb2.HeartbeatRequest.SerializeToString,
            indexify_dot_proto_dot_executor__api__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def poll_commands(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/executor_api_pb.ExecutorAPI/poll_commands",
            indexify_dot_proto_dot_executor__api__pb2.PollCommandsRequest.SerializeToString,
            indexify_dot_proto_dot_executor__api__pb2.PollCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def poll_allocation_results(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/executor_api_pb.ExecutorAPI/poll_allocation_results",
            indexify_dot_proto_dot_executor__api__pb2.PollAllocationResultsRequest.SerializeToString,
            indexify_dot_proto_dot_executor__api__pb2.PollAllocationResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
