#[allow(non_camel_case_types)] // The autogenerated code uses snake_case types in some cases
pub mod executor_api_pb {
    tonic::include_proto!("executor_api_pb");
}

use std::{collections::HashMap, pin::Pin, sync::Arc, vec};

use data_model::{
    DataPayload, ExecutorId, ExecutorMetadata, ExecutorMetadataBuilder, FunctionExecutor,
    FunctionExecutorId, FunctionURI, GraphVersion, NodeOutputBuilder, OutputPayload,
    TaskDiagnostics, TaskOutcome, TaskOutputsIngestionStatus, TaskStatus,
};
use executor_api_pb::{
    executor_api_server::ExecutorApi, AllowedFunction, DataPayloadEncoding, DesiredExecutorState,
    ExecutorState, ExecutorStatus, FunctionExecutorDescription, FunctionExecutorResources,
    FunctionExecutorStatus, GetDesiredExecutorStatesRequest, HostResources, OutputEncoding,
    ReportExecutorStateRequest, ReportExecutorStateResponse, ReportTaskOutcomeRequest,
    ReportTaskOutcomeResponse,
};
use metrics::api_io_stats;
use state_store::{
    requests::{IngestTaskOutputsRequest, RequestPayload, StateMachineUpdateRequest},
    IndexifyState,
};
use tokio::sync::watch;
use tokio_stream::{wrappers::WatchStream, Stream};
use tonic::{Request, Response, Status};
use tracing::{debug, error, info, trace, warn};

use crate::executors::ExecutorManager;

impl TryFrom<AllowedFunction> for FunctionURI {
    type Error = anyhow::Error;

    fn try_from(allowed_function: AllowedFunction) -> Result<Self, Self::Error> {
        let namespace = allowed_function
            .namespace
            .ok_or(anyhow::anyhow!("namespace is required"))?;
        let compute_graph_name = allowed_function
            .graph_name
            .ok_or(anyhow::anyhow!("compute_graph_name is required"))?;
        let compute_fn_name = allowed_function
            .function_name
            .ok_or(anyhow::anyhow!("compute_fn_name is required"))?;
        let version = allowed_function.graph_version.map(|v| GraphVersion(v));
        Ok(FunctionURI {
            namespace,
            compute_graph_name,
            compute_fn_name,
            version,
        })
    }
}

impl TryFrom<data_model::HostResources> for HostResources {
    type Error = anyhow::Error;

    fn try_from(from: data_model::HostResources) -> Result<Self, Self::Error> {
        Ok(HostResources {
            cpu_count: Some(from.cpu_count),
            memory_bytes: Some(from.memory_bytes),
            disk_bytes: Some(from.disk_bytes),
            gpu: from.gpu.map(|g| g.try_into()).transpose()?,
        })
    }
}

impl TryFrom<HostResources> for data_model::HostResources {
    type Error = anyhow::Error;

    fn try_from(from: HostResources) -> Result<Self, Self::Error> {
        let cpu = from
            .cpu_count
            .ok_or(anyhow::anyhow!("cpu_count is required"))?;
        let memory = from
            .memory_bytes
            .ok_or(anyhow::anyhow!("memory_bytes is required"))?;
        let disk = from
            .disk_bytes
            .ok_or(anyhow::anyhow!("disk_bytes is required"))?;
        let gpu = from.gpu.map(|g| g.try_into()).transpose()?;
        Ok(data_model::HostResources {
            cpu_count: cpu,
            memory_bytes: memory,
            disk_bytes: disk,
            gpu,
        })
    }
}

impl TryFrom<String> for DataPayloadEncoding {
    type Error = anyhow::Error;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        match value.as_str() {
            "application/json" => Ok(DataPayloadEncoding::Utf8Json),
            "application/octet-stream" => Ok(DataPayloadEncoding::BinaryPickle),
            "text/plain" => Ok(DataPayloadEncoding::Utf8Text),
            _ => Err(anyhow::anyhow!("unknown data payload encoding")),
        }
    }
}

impl From<ExecutorStatus> for data_model::ExecutorState {
    fn from(status: ExecutorStatus) -> Self {
        match status {
            ExecutorStatus::StartingUp => data_model::ExecutorState::StartingUp,
            ExecutorStatus::Running => data_model::ExecutorState::Running,
            ExecutorStatus::Drained => data_model::ExecutorState::Drained,
            ExecutorStatus::Stopping => data_model::ExecutorState::Stopping,
            ExecutorStatus::Stopped => data_model::ExecutorState::Stopped,
            ExecutorStatus::Unknown => data_model::ExecutorState::Unknown,
        }
    }
}

impl TryFrom<data_model::GpuResources> for executor_api_pb::GpuResources {
    type Error = anyhow::Error;

    fn try_from(gpu_resources: data_model::GpuResources) -> Result<Self, Self::Error> {
        if gpu_resources.count == 0 {
            return Err(anyhow::anyhow!("data_model gpu_resources.count is 0"));
        }
        let proto_model = match gpu_resources.model.as_str() {
            data_model::GPU_MODEL_NVIDIA_A100_40GB => Ok(executor_api_pb::GpuModel::NvidiaA10040gb),
            data_model::GPU_MODEL_NVIDIA_A100_80GB => Ok(executor_api_pb::GpuModel::NvidiaA10080gb),
            data_model::GPU_MODEL_NVIDIA_H100_80GB => Ok(executor_api_pb::GpuModel::NvidiaH10080gb),
            _ => Err(anyhow::anyhow!("unknown data_model gpu_resources.model")),
        }?;
        Ok(executor_api_pb::GpuResources {
            count: Some(gpu_resources.count),
            model: Some(proto_model.into()),
        })
    }
}

impl TryFrom<executor_api_pb::GpuResources> for data_model::GpuResources {
    type Error = anyhow::Error;

    fn try_from(gpu_resources: executor_api_pb::GpuResources) -> Result<Self, Self::Error> {
        if gpu_resources.count() == 0 {
            return Err(anyhow::anyhow!("proto gpu_resources.count is 0"));
        }
        let str_model = match gpu_resources.model() {
            executor_api_pb::GpuModel::Unknown => {
                Err(anyhow::anyhow!("proto gpu_resources.model is unknown"))
            }
            executor_api_pb::GpuModel::NvidiaA10040gb => Ok(data_model::GPU_MODEL_NVIDIA_A100_40GB),
            executor_api_pb::GpuModel::NvidiaA10080gb => Ok(data_model::GPU_MODEL_NVIDIA_A100_80GB),
            executor_api_pb::GpuModel::NvidiaH10080gb => Ok(data_model::GPU_MODEL_NVIDIA_H100_80GB),
            executor_api_pb::GpuModel::NvidiaTeslaT4 => Ok(data_model::GPU_MODEL_NVIDIA_TESLA_T4),
        }?;
        Ok(data_model::GpuResources {
            count: gpu_resources.count(),
            model: str_model.into(),
        })
    }
}

impl From<FunctionExecutorStatus> for data_model::FunctionExecutorStatus {
    fn from(status: FunctionExecutorStatus) -> Self {
        match status {
            FunctionExecutorStatus::StartingUp => data_model::FunctionExecutorStatus::StartingUp,
            FunctionExecutorStatus::StartupFailedCustomerError => {
                data_model::FunctionExecutorStatus::StartupFailedCustomerError
            }
            FunctionExecutorStatus::StartupFailedPlatformError => {
                data_model::FunctionExecutorStatus::StartupFailedPlatformError
            }
            FunctionExecutorStatus::Idle => data_model::FunctionExecutorStatus::Idle,
            FunctionExecutorStatus::RunningTask => data_model::FunctionExecutorStatus::RunningTask,
            FunctionExecutorStatus::Stopping => data_model::FunctionExecutorStatus::Stopping,
            FunctionExecutorStatus::Stopped => data_model::FunctionExecutorStatus::Stopped,
            FunctionExecutorStatus::Unhealthy => data_model::FunctionExecutorStatus::Unhealthy,
            FunctionExecutorStatus::Shutdown => data_model::FunctionExecutorStatus::Shutdown,
            FunctionExecutorStatus::Unknown => data_model::FunctionExecutorStatus::Unknown,
        }
    }
}

impl From<data_model::NodeRetryPolicy> for executor_api_pb::TaskRetryPolicy {
    fn from(from: data_model::NodeRetryPolicy) -> Self {
        executor_api_pb::TaskRetryPolicy {
            max_retries: Some(from.max_retries),
            initial_delay_ms: Some(from.initial_delay_ms),
            delay_multiplier: Some(from.delay_multiplier),
            max_delay_ms: Some(from.max_delay_ms),
        }
    }
}

impl TryFrom<FunctionExecutorResources> for data_model::NodeResources {
    type Error = anyhow::Error;

    fn try_from(from: FunctionExecutorResources) -> Result<Self, Self::Error> {
        let cpu_ms_per_sec = from
            .cpu_ms_per_sec
            .ok_or(anyhow::anyhow!("cpu_ms_per_sec is required"))?;
        let memory_bytes = from
            .memory_bytes
            .ok_or(anyhow::anyhow!("memory_bytes is required"))?;
        let ephemeral_disk_bytes = from
            .disk_bytes
            .ok_or(anyhow::anyhow!("disk_bytes is required"))?;
        let gpu_count = from.gpu_count.unwrap_or(0);
        Ok(data_model::NodeResources {
            cpu_ms_per_sec,
            memory_mb: (memory_bytes / 1024 / 1024) as u32,
            ephemeral_disk_mb: (ephemeral_disk_bytes / 1024 / 1024) as u32,
            gpu: if gpu_count > 0 {
                Some(data_model::NodeGPUs {
                    count: gpu_count,
                    // TODO: Add GPU model in FunctionExecutorResources
                    model: "unknown".to_string(),
                })
            } else {
                None
            },
        })
    }
}

impl TryFrom<data_model::NodeResources> for FunctionExecutorResources {
    type Error = anyhow::Error;

    fn try_from(from: data_model::NodeResources) -> Result<Self, Self::Error> {
        Ok(FunctionExecutorResources {
            cpu_ms_per_sec: Some(from.cpu_ms_per_sec),
            memory_bytes: Some(from.memory_mb as u64 * 1024 * 1024),
            disk_bytes: Some(from.ephemeral_disk_mb as u64 * 1024 * 1024),
            gpu_count: match from.gpu {
                Some(gpus) => Some(gpus.count),
                None => Some(0),
            },
        })
    }
}

impl TryFrom<ExecutorState> for ExecutorMetadata {
    type Error = anyhow::Error;

    fn try_from(executor_state: ExecutorState) -> Result<Self, Self::Error> {
        let mut executor_metadata = ExecutorMetadataBuilder::default();
        let executor_id = executor_state
            .executor_id
            .clone()
            .map(ExecutorId::new)
            .ok_or(anyhow::anyhow!("executor_id is required"))?;
        executor_metadata.id(executor_id.clone());
        executor_metadata.state(executor_state.status().into());
        executor_metadata.development_mode(
            executor_state
                .development_mode
                .ok_or(anyhow::anyhow!("development_mode is required"))?,
        );
        if let Some(state_hash) = executor_state.state_hash.clone() {
            executor_metadata.state_hash(state_hash);
        }
        // FIXME: ignoring Executor flavor for now.
        if let Some(executor_version) = executor_state.version {
            executor_metadata.executor_version(executor_version);
        }
        let mut allowed_functions = Vec::new();
        for function in executor_state.allowed_functions {
            allowed_functions.push(FunctionURI::try_from(function)?);
        }
        if allowed_functions.is_empty() {
            executor_metadata.function_allowlist(None);
        } else {
            executor_metadata.function_allowlist(Some(allowed_functions));
        }
        if let Some(addr) = executor_state.hostname {
            executor_metadata.addr(addr);
        }
        let mut labels = HashMap::new();
        for (key, value) in executor_state.labels {
            labels.insert(key, serde_json::Value::String(value));
        }
        executor_metadata.labels(labels);
        let mut function_executors = HashMap::new();
        for function_executor_state in executor_state.function_executor_states {
            let function_executor_description = function_executor_state
                .description
                .clone()
                .ok_or(anyhow::anyhow!("description is required"))?;
            let mut function_executor = FunctionExecutor::try_from(function_executor_description)?;
            function_executor.status = function_executor_state.status().into();
            function_executors.insert(function_executor.id.clone(), function_executor);
        }
        executor_metadata.function_executors(function_executors);
        if let Some(host_resources) = executor_state.free_resources {
            let cpu = host_resources
                .cpu_count
                .ok_or(anyhow::anyhow!("cpu_count is required"))?;
            let memory = host_resources
                .memory_bytes
                .ok_or(anyhow::anyhow!("memory_bytes is required"))?;
            let disk = host_resources
                .disk_bytes
                .ok_or(anyhow::anyhow!("disk_bytes is required"))?;
            // Ignore errors during conversion as they are expected e.g. if Executor GPU
            // model is unknown.
            let gpu = match host_resources.gpu {
                Some(gpu_resources) => gpu_resources.try_into().ok(),
                None => None,
            };
            executor_metadata.host_resources(data_model::HostResources {
                cpu_count: cpu,
                memory_bytes: memory,
                disk_bytes: disk,
                gpu,
            });
            executor_metadata.host_resources(host_resources.try_into()?);
        }
        if let Some(server_clock) = executor_state.server_clock {
            executor_metadata.clock(server_clock);
        }
        Ok(executor_metadata.build()?)
    }
}

impl TryFrom<FunctionExecutorDescription> for FunctionExecutor {
    type Error = anyhow::Error;

    fn try_from(
        function_executor_description: FunctionExecutorDescription,
    ) -> Result<Self, Self::Error> {
        let id = function_executor_description
            .id
            .map(|id| FunctionExecutorId::new(id))
            .ok_or(anyhow::anyhow!("id is required"))?;
        let namespace = function_executor_description
            .namespace
            .ok_or(anyhow::anyhow!("namespace is required"))?;
        let compute_graph_name = function_executor_description
            .graph_name
            .ok_or(anyhow::anyhow!("compute_graph_name is required"))?;
        let compute_fn_name = function_executor_description
            .function_name
            .ok_or(anyhow::anyhow!("compute_fn_name is required"))?;
        let version = function_executor_description
            .graph_version
            .map(GraphVersion)
            .ok_or(anyhow::anyhow!("version is required"))?;

        Ok(FunctionExecutor {
            id,
            namespace,
            compute_graph_name,
            compute_fn_name,
            version,
            // is set when the parent proto message FunctionExecutorStatus is converted
            status: data_model::FunctionExecutorStatus::Unknown,
        })
    }
}

pub struct ExecutorAPIService {
    indexify_state: Arc<IndexifyState>,
    executor_manager: Arc<ExecutorManager>,
    api_metrics: Arc<api_io_stats::Metrics>,
    blob_storage: Arc<blob_store::BlobStorage>,
}

impl ExecutorAPIService {
    pub fn new(
        indexify_state: Arc<IndexifyState>,
        executor_manager: Arc<ExecutorManager>,
        api_metrics: Arc<api_io_stats::Metrics>,
        blob_storage: Arc<blob_store::BlobStorage>,
    ) -> Self {
        Self {
            indexify_state,
            executor_manager,
            api_metrics,
            blob_storage,
        }
    }
}

#[tonic::async_trait]
impl ExecutorApi for ExecutorAPIService {
    #[allow(non_camel_case_types)] // The autogenerated code in the trait uses snake_case types in some cases
    type get_desired_executor_statesStream =
        Pin<Box<dyn Stream<Item = Result<DesiredExecutorState, Status>> + Send>>;

    async fn report_executor_state(
        &self,
        request: Request<ReportExecutorStateRequest>,
    ) -> Result<Response<ReportExecutorStateResponse>, Status> {
        let executor_state = request
            .get_ref()
            .executor_state
            .clone()
            .ok_or(Status::invalid_argument("executor_state is required"))?;
        let executor_id = executor_state
            .executor_id
            .clone()
            .ok_or(Status::invalid_argument("executor_id is required"))?;
        let executor_id = ExecutorId::new(executor_id);

        trace!(
            executor_id = executor_id.get(),
            "Got report_executor_state request"
        );
        let executor_metadata = ExecutorMetadata::try_from(executor_state)
            .map_err(|e| Status::invalid_argument(e.to_string()))?;
        self.executor_manager
            .heartbeat(executor_metadata)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        Ok(Response::new(ReportExecutorStateResponse {}))
    }

    async fn get_desired_executor_states(
        &self,
        request: Request<GetDesiredExecutorStatesRequest>,
    ) -> Result<Response<Self::get_desired_executor_statesStream>, Status> {
        let executor_id = request
            .get_ref()
            .executor_id
            .clone()
            .ok_or(Status::invalid_argument("executor_id is required"))?;
        let executor_id = ExecutorId::new(executor_id);

        trace!(
            executor_id = executor_id.get(),
            "Got get_desired_executor_states request",
        );

        let mut state_rx = match self.executor_manager.subscribe(&executor_id).await {
            Some(state_rx) => state_rx,
            None => {
                let msg = "executor not found, or not yet registered";
                warn!(
                    executor_id = executor_id.get(),
                    "get_desired_executor_states: {}", msg
                );
                return Err(Status::not_found(msg));
            }
        };

        let (tx, rx) = watch::channel(Result::Ok(DesiredExecutorState {
            function_executors: vec![],
            task_allocations: vec![],
            clock: Some(0),
        }));
        let executor_manager = self.executor_manager.clone();
        tokio::spawn(async move {
            // 1. Mark the state as changed to trigger the first change notification to the
            //    executor. This is important because between the report_executor_state and
            //    the get_desired_executor_states requests, the executor state may received
            //    a new desired state.
            state_rx.mark_changed();
            loop {
                // 2. Wait for a state change for this executor
                if let Err(err) = state_rx.changed().await {
                    info!(
                        executor_id = executor_id.get(),
                        "get_desired_executor_states: state machine watcher closing: {}", err
                    );
                    break;
                }

                // 3. Get the latest state
                let desired_state: DesiredExecutorState = match executor_manager
                    .get_executor_state(&executor_id)
                    .await
                    .try_into()
                {
                    Ok(desired_state) => desired_state,
                    Err(err) => {
                        info!(
                            executor_id = executor_id.get(),
                            "get_desired_executor_states: failed to convert desired state, ignoring: {:?}", err
                        );
                        continue;
                    }
                };

                debug!(
                    executor_id = executor_id.get(),
                    "get_desired_executor_states: got desired state: {:#?}", desired_state
                );

                // 4. Send the state to the executor
                if let Err(err) = tx.send(Ok(desired_state)) {
                    info!(
                        executor_id = executor_id.get(),
                        "get_desired_executor_states: grpc stream closing: {}", err
                    );
                    break;
                }
            }
        });

        let output_stream = WatchStream::from_changes(rx);
        Ok(Response::new(
            Box::pin(output_stream) as Self::get_desired_executor_statesStream
        ))
    }

    async fn report_task_outcome(
        &self,
        request: Request<ReportTaskOutcomeRequest>,
    ) -> Result<Response<ReportTaskOutcomeResponse>, Status> {
        self.api_metrics
            .fn_outputs
            .add(request.get_ref().fn_outputs.len() as u64, &[]);

        let task_id = request
            .get_ref()
            .task_id
            .clone()
            .ok_or(Status::invalid_argument("task_id is required"))?;

        let task_outcome =
            executor_api_pb::TaskOutcome::try_from(request.get_ref().outcome.unwrap_or(0))
                .map_err(|e| Status::invalid_argument(e.to_string()))?;

        let executor_id = request
            .get_ref()
            .executor_id
            .clone()
            .ok_or(Status::invalid_argument("executor_id is required"))?;
        let namespace = request
            .get_ref()
            .namespace
            .clone()
            .ok_or(Status::invalid_argument("namespace is required"))?;
        let compute_graph = request
            .get_ref()
            .graph_name
            .clone()
            .ok_or(Status::invalid_argument("compute_graph is required"))?;
        let compute_fn = request
            .get_ref()
            .function_name
            .clone()
            .ok_or(Status::invalid_argument("compute_fn is required"))?;
        let invocation_id = request
            .get_ref()
            .graph_invocation_id
            .clone()
            .ok_or(Status::invalid_argument("graph_invocation_id is required"))?;
        let task = self
            .indexify_state
            .reader()
            .get_task(
                &namespace,
                &compute_graph,
                &invocation_id,
                &compute_fn,
                &task_id,
            )
            .map_err(|e| Status::internal(e.to_string()))?;
        if task.is_none() {
            warn!("Task not found for task_id: {}", task_id);
            return Ok(Response::new(ReportTaskOutcomeResponse {}));
        }
        let mut task = task.unwrap();
        match task_outcome {
            executor_api_pb::TaskOutcome::Success => {
                task.outcome = TaskOutcome::Success;
            }
            executor_api_pb::TaskOutcome::Failure => {
                task.outcome = TaskOutcome::Failure;
            }
            executor_api_pb::TaskOutcome::Unknown => {
                task.outcome = TaskOutcome::Unknown;
            }
        }
        task.output_status = TaskOutputsIngestionStatus::Ingested;
        task.status = TaskStatus::Completed;

        let mut node_outputs = Vec::new();
        for output in request.get_ref().fn_outputs.clone() {
            let path = output
                .path
                .or(output.uri)
                .ok_or(Status::invalid_argument("path or uri is required"))?;

            let path = blob_store_url_to_path(
                &path,
                &self.blob_storage.get_url_scheme(),
                &self.blob_storage.get_url(),
            );
            let size = output
                .size
                .ok_or(Status::invalid_argument("size is required"))?;
            let sha256_hash = output
                .sha256_hash
                .ok_or(Status::invalid_argument("sha256_hash is required"))?;
            let data_payload = DataPayload {
                path,
                size,
                sha256_hash,
            };
            let encoding_str = match output.encoding {
                Some(value) => {
                    let output_encoding = DataPayloadEncoding::try_from(value)
                        .map_err(|e| Status::invalid_argument(e.to_string()))?;
                    match output_encoding {
                        DataPayloadEncoding::Utf8Json => Ok("application/json"),
                        DataPayloadEncoding::BinaryPickle => Ok("application/octet-stream"),
                        DataPayloadEncoding::Utf8Text => Ok("text/plain"),
                        DataPayloadEncoding::Unknown => {
                            Err(Status::invalid_argument("unknown data payload encoding"))
                        }
                    }
                }
                // Fallback to the deprecated request encoding if not set
                None => match request.get_ref().output_encoding {
                    Some(value) => {
                        let output_encoding = OutputEncoding::try_from(value)
                            .map_err(|e| Status::invalid_argument(e.to_string()))?;
                        match output_encoding {
                            OutputEncoding::Json => Ok("application/json"),
                            OutputEncoding::Pickle => Ok("application/octet-stream"),
                            OutputEncoding::Binary => Ok("application/octet-stream"),
                            OutputEncoding::Unknown => {
                                Err(Status::invalid_argument("unknown request output encoding"))
                            }
                        }
                    }
                    None => Err(Status::invalid_argument(
                        "data payload encoding or request output encoding is required",
                    )),
                },
            }?;

            let node_output = NodeOutputBuilder::default()
                .namespace(namespace.to_string())
                .compute_graph_name(compute_graph.to_string())
                .invocation_id(invocation_id.to_string())
                .compute_fn_name(compute_fn.to_string())
                .payload(OutputPayload::Fn(data_payload))
                .encoding(encoding_str.to_string())
                .build()
                .map_err(|e| Status::internal(e.to_string()))?;
            node_outputs.push(node_output);
        }

        if request.get_ref().next_functions.len() > 0 {
            let node_output = NodeOutputBuilder::default()
                .namespace(namespace.to_string())
                .compute_graph_name(compute_graph.to_string())
                .invocation_id(invocation_id.to_string())
                .compute_fn_name(compute_fn.to_string())
                .payload(OutputPayload::Router(data_model::RouterOutput {
                    edges: request.get_ref().next_functions.clone(),
                }))
                .build()
                .map_err(|e| Status::internal(e.to_string()))?;
            node_outputs.push(node_output);
        }
        let task_diagnostic = TaskDiagnostics {
            stdout: prepare_data_payload(
                request.get_ref().stdout.clone(),
                &self.blob_storage.get_url_scheme(),
                &self.blob_storage.get_url(),
            ),
            stderr: prepare_data_payload(
                request.get_ref().stderr.clone(),
                &self.blob_storage.get_url_scheme(),
                &self.blob_storage.get_url(),
            ),
        };
        task.diagnostics = Some(task_diagnostic.clone());
        let request = RequestPayload::IngestTaskOutputs(IngestTaskOutputsRequest {
            namespace: namespace.to_string(),
            compute_graph: compute_graph.to_string(),
            compute_fn: compute_fn.to_string(),
            invocation_id: invocation_id.to_string(),
            task: task.clone(),
            node_outputs,
            executor_id: ExecutorId::new(executor_id.clone()),
        });

        let sm_req = StateMachineUpdateRequest {
            payload: request,
            processed_state_changes: vec![],
        };

        self.indexify_state
            .write(sm_req)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;
        Ok(Response::new(ReportTaskOutcomeResponse {}))
    }
}

fn prepare_data_payload(
    msg: Option<executor_api_pb::DataPayload>,
    blob_store_url_scheme: &str,
    blob_store_url: &str,
) -> Option<data_model::DataPayload> {
    if msg.is_none() {
        return None;
    }
    let msg = msg.unwrap();
    if msg.uri.is_none() && msg.path.is_none() {
        return None;
    }
    if msg.size.as_ref().is_none() {
        return None;
    }
    if msg.sha256_hash.as_ref().is_none() {
        return None;
    }

    // Fallback to deprecated path if uri is not set.
    let path = msg.uri.or(msg.path).unwrap();
    Some(data_model::DataPayload {
        path: blob_store_url_to_path(&path, blob_store_url_scheme, blob_store_url),
        size: msg.size.unwrap(),
        sha256_hash: msg.sha256_hash.unwrap(),
    })
}

pub fn blob_store_path_to_url(
    path: &str,
    blob_store_url_scheme: &str,
    blob_store_url: &str,
) -> String {
    if blob_store_url_scheme == "file" {
        // Local file blob store implementation is always using absolute paths without
        // "/"" prefix. The paths are not relative to the configure blob_store_url path.
        return format!("{}:///{}", blob_store_url_scheme, path);
    } else if blob_store_url_scheme == "s3" {
        // S3 blob store implementation uses paths relative to its bucket from
        // blob_store_url.
        return format!(
            "{}://{}/{}",
            blob_store_url_scheme,
            bucket_name_from_s3_blob_store_url(blob_store_url),
            path
        );
    } else {
        return format!("not supported blob store scheme: {}", blob_store_url_scheme);
    }
}

pub fn blob_store_url_to_path(
    url: &str,
    blob_store_url_scheme: &str,
    blob_store_url: &str,
) -> String {
    if blob_store_url_scheme == "file" {
        // Local file blob store implementation is always using absolute paths without
        // "/"" prefix. The paths are not relative to the configure blob_store_url path.
        return url
            .strip_prefix(&format!("{}:///", blob_store_url_scheme).to_string())
            // The url doesn't include blob_store_scheme if this payload was uploaded to server
            // instead of directly to blob storage.
            .unwrap_or(url)
            .to_string();
    } else if blob_store_url_scheme == "s3" {
        // S3 blob store implementation uses paths relative to its bucket from
        // blob_store_url.
        return url
            .strip_prefix(
                &format!(
                    "{}://{}/",
                    blob_store_url_scheme,
                    bucket_name_from_s3_blob_store_url(blob_store_url)
                )
                .to_string(),
            )
            // The url doesn't include blob_store_url if this payload was uploaded to server instead
            // of directly to blob storage.
            .unwrap_or(url)
            .to_string();
    } else {
        return format!("not supported blob store scheme: {}", blob_store_url_scheme);
    }
}

fn bucket_name_from_s3_blob_store_url(blob_store_url: &str) -> String {
    match url::Url::parse(blob_store_url) {
        Ok(url) => match url.host_str() {
            Some(bucket) => bucket.into(),
            None => {
                error!("Didn't find bucket name in S3 url: {}", blob_store_url);
                return String::new();
            }
        },
        Err(e) => {
            error!(
                "Failed to parse blob_store_url: {}. Error: {}",
                blob_store_url, e
            );
            return String::new();
        }
    }
}
