[package]
name = "state_store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = { workspace = true }
data_model = { workspace = true }
indexify_utils = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
chrono = "0.4.38"


[dev-dependencies]
tempfile = { workspace = true }




