---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  ports:
    - port: 8950
  selector:
    app.kubernetes.io/component: coordinator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  labels:
    app.kubernetes.io/component: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: coordinator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: coordinator

    spec:
      initContainers:
        - name: concat
          image: alpine:3
          command: ['/bin/sh', '-c']
          args:
            - find /fragments -type f | xargs -I{} sh -c "cat {}; echo ''" > /config/config.yaml

          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /fragments
              name: fragments

      containers:
        - name: indexify
          image: tensorlake/indexify:stable

          command: ['indexify']
          args:
            - coordinator
            - --config-path
            - ./config/config.yaml

          volumeMounts:
            - mountPath: /indexify/config
              name: config
              readOnly: true
            - mountPath: /data
              name: data

      volumes:
        - name: fragments
          configMap:
            name: indexify
        - name: config
          emptyDir: {}
        - name: data
          emptyDir: {}
