FROM ubuntu:22.04

RUN apt update

RUN apt install -y lsb-release ca-certificates apt-transport-https

RUN update-ca-certificates

RUN echo "deb [trusted=yes] https://cf-repo.diptanu-6d5.workers.dev/repo $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/indexify-repo.list && \
    apt-get update -y && \
    apt-get install -y indexify-server && \
    apt-get -y clean

WORKDIR /indexify

COPY sample_config.yaml ./config/indexify.yaml

ENTRYPOINT [ "indexify-server" ]
