name: Build on merge

on:
  push:
    branches:
      - 'main'
      - 'server-sse-stream-stable'
      - 'troubleshoot-ecr-builds'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build_dev_ecr:
    uses: ./.github/workflows/build_ecr_image.yaml
    with: 
      environment: dev
    secrets: inherit

  build_prod_ecr:
    uses: ./.github/workflows/build_ecr_image.yaml
    with: 
      environment: prod
    secrets: inherit
