name: Publish Python SDK

on: workflow_dispatch

jobs:
  publish-to-pypi:
    name: Publish Python SDK
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/indexify
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install pypa/build
        run: cd sdk-py && python3 -m pip install poetry --user && python3 -m poetry build && cd ..
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: sdk-py/dist/
